- name: Demo on Play Variables
  host: all
  vars:
    URL: play.example.com
  task:
    - debug:
        msg: URL = {{ URL }}
- name: Demo on task variable
  hosts: all
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
      var:
        URl: tasks.examples.com

- name: Demo on CLI variable
    hosts: all
    vars:
     - vars.yml
    tasks:
      - name: Print URL
        debug:
          msg: URL1 = {{ URL1 }}


- name: Demo on Inventory variable
    hosts: all
    tasks:
      - name: Print URL
        debug:
          msg: URL2 = {{ URL2 }}

- name: Demo on file variable
    hosts: all
    tasks:
      - name: Print URL
        debug:
          msg: URL_FILE = {{ URL_FILE }}
- name: prompt for Input
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: yes
  tasks:
    - name: Print URL
      debug:
        msg: URL {{ URL }}

