- name: Demo on run time vars
  hosts: all
  task:
    - name: Grab uptime
      shell: uptime
      register: OUT

    - name: print uptime
      debug:
        msg: "{{OUT.stdout}}"

    - name: Set a variable
       set_fact:
        UPTIME_OUTPUT: "{{OUT.stdout}}"

    - name: Print uptime
       debug:
         msg: "uptime = {{UPTIME_OUTPUT}}"